import { Project } from '@/types/project';
import { TimelineItem, ChangeRequest, Material } from '@/types/timeline';
import { ChatMessage } from '@/types/assistant';
import { UploadStep, StorageUsage } from '@/types/common';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    user_id: 'user-001',
    title: '우리집 25평 인테리어',
    address: '서울시 강남구 역삼동',
    contractor_name: '행복건설',
    contract_amount: 28000000,
    start_date: '2024-03-15',
    end_date: '2024-04-30',
    status: 'active',
    storage_size_bytes: 1288490188,
    created_at: '2024-03-10T09:00:00Z',
    updated_at: '2024-03-25T14:30:00Z',
    timeline_count: 585,
    photo_count: 127,
  },
  {
    id: 'proj-002',
    user_id: 'user-001',
    title: '원룸 도배+장판',
    address: '서울시 관악구 봉천동',
    contractor_name: '깔끔인테리어',
    contract_amount: 3500000,
    start_date: '2024-02-01',
    end_date: '2024-02-05',
    status: 'completed',
    storage_size_bytes: 234881024,
    created_at: '2024-01-28T10:00:00Z',
    updated_at: '2024-02-06T09:00:00Z',
    timeline_count: 112,
    photo_count: 23,
  },
];

export const MOCK_TIMELINE_ITEMS: TimelineItem[] = [
  {
    id: 'tl-001',
    project_id: 'proj-001',
    item_type: 'message',
    source: 'kakao_chat',
    occurred_at: '2024-03-15T09:30:00Z',
    sender_name: '홍길동',
    message_content: '사장님 오늘 철거 시작하시나요?',
    process_category: 'demolition',
    category_confirmed: true,
    created_at: '2024-03-15T09:30:00Z',
  },
  {
    id: 'tl-002',
    project_id: 'proj-001',
    item_type: 'message',
    source: 'kakao_chat',
    occurred_at: '2024-03-15T12:30:00Z',
    sender_name: '김시공',
    message_content: '거실 철거 완료했습니다. 화장실은 내일 할게요.',
    process_category: 'demolition',
    category_confirmed: true,
    created_at: '2024-03-15T12:30:00Z',
  },
  {
    id: 'tl-003',
    project_id: 'proj-001',
    item_type: 'photo',
    source: 'photo_upload',
    occurred_at: '2024-03-15T12:31:00Z',
    sender_name: '김시공',
    file_url: '/mock/photo1.jpg',
    file_thumbnail_url: '/mock/photo1_thumb.jpg',
    original_filename: 'IMG_2024.jpg',
    process_category: 'demolition',
    category_confirmed: true,
    created_at: '2024-03-15T12:31:00Z',
  },
  {
    id: 'tl-004',
    project_id: 'proj-001',
    item_type: 'message',
    source: 'kakao_chat',
    occurred_at: '2024-03-15T13:00:00Z',
    sender_name: '홍길동',
    message_content: '벽지 밑에 곰팡이가 있는 것 같은데 확인해주실 수 있나요?',
    process_category: 'demolition',
    category_confirmed: false,
    created_at: '2024-03-15T13:00:00Z',
  },
  {
    id: 'tl-005',
    project_id: 'proj-001',
    item_type: 'message',
    source: 'kakao_chat',
    occurred_at: '2024-03-18T09:00:00Z',
    sender_name: '김시공',
    message_content: '오늘부터 전기 작업 들어갑니다',
    process_category: 'electrical',
    category_confirmed: true,
    created_at: '2024-03-18T09:00:00Z',
  },
  {
    id: 'tl-006',
    project_id: 'proj-001',
    item_type: 'memo',
    source: 'manual',
    occurred_at: '2024-03-18T09:35:00Z',
    sender_name: '나',
    message_content: '콘센트 3개 추가 요청 (9만원 추가)',
    process_category: 'electrical',
    category_confirmed: true,
    created_at: '2024-03-18T09:35:00Z',
  },
  {
    id: 'tl-007',
    project_id: 'proj-001',
    item_type: 'message',
    source: 'kakao_chat',
    occurred_at: '2024-03-20T10:00:00Z',
    sender_name: '김시공',
    message_content: '목공 작업 시작합니다. 거실 몰딩부터 할게요.',
    process_category: 'carpentry',
    category_confirmed: true,
    created_at: '2024-03-20T10:00:00Z',
  },
  {
    id: 'tl-008',
    project_id: 'proj-001',
    item_type: 'photo',
    source: 'photo_upload',
    occurred_at: '2024-03-20T15:00:00Z',
    sender_name: '김시공',
    file_url: '/mock/photo2.jpg',
    file_thumbnail_url: '/mock/photo2_thumb.jpg',
    original_filename: 'IMG_2031.jpg',
    process_category: 'carpentry',
    category_confirmed: false,
    created_at: '2024-03-20T15:00:00Z',
  },
  {
    id: 'tl-009',
    project_id: 'proj-001',
    item_type: 'document',
    source: 'pdf_upload',
    occurred_at: '2024-03-10T11:00:00Z',
    sender_name: '홍길동',
    file_url: '/mock/estimate.pdf',
    original_filename: '행복건설_견적서.pdf',
    process_category: 'other',
    category_confirmed: true,
    created_at: '2024-03-10T11:00:00Z',
  },
  {
    id: 'tl-010',
    project_id: 'proj-001',
    item_type: 'change_request',
    source: 'manual',
    occurred_at: '2024-03-25T14:00:00Z',
    sender_name: '홍길동',
    message_content: '화장실 타일 변경 (기존 단종으로 인한 변경)',
    process_category: 'tiling',
    category_confirmed: true,
    created_at: '2024-03-25T14:00:00Z',
  },
];

export const MOCK_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'cr-001',
    project_id: 'proj-001',
    description: '콘센트 3개 추가',
    reason: '전기 작업 중 추가 요청',
    cost_impact: 90000,
    status: 'confirmed',
    requested_by: 'consumer',
    requested_at: '2024-03-18T09:35:00Z',
    confirmed_at: '2024-03-18T10:00:00Z',
  },
  {
    id: 'cr-002',
    project_id: 'proj-001',
    description: '싱크대 위치 변경',
    reason: '배관 위치 차이로 인한 변경',
    cost_impact: 0,
    status: 'confirmed',
    requested_by: 'contractor',
    requested_at: '2024-03-16T11:00:00Z',
    confirmed_at: '2024-03-16T14:00:00Z',
  },
  {
    id: 'cr-003',
    project_id: 'proj-001',
    description: '화장실 타일 변경',
    reason: '기존 타일 단종',
    cost_impact: 300000,
    status: 'pending',
    requested_by: 'contractor',
    requested_at: '2024-03-25T14:00:00Z',
  },
];

export const MOCK_MATERIALS: Material[] = [
  {
    id: 'mat-001',
    project_id: 'proj-001',
    name: '포세린 타일 600x600',
    category: 'tiling',
    specification: '이탈리아산 무광',
    unit_price: 35000,
    quantity: 42,
    unit: '장',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'mat-002',
    project_id: 'proj-001',
    name: '실크 벽지',
    category: 'painting',
    specification: 'LG하우시스 ZN062',
    unit_price: 25000,
    quantity: 30,
    unit: '롤',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'mat-003',
    project_id: 'proj-001',
    name: '전선 HIV 2.5sq',
    category: 'electrical',
    specification: '대한전선',
    unit_price: 800,
    quantity: 200,
    unit: 'm',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'mat-004',
    project_id: 'proj-001',
    name: '강화마루',
    category: 'flooring',
    specification: '한화 L4301',
    unit_price: 18000,
    quantity: 25,
    unit: '평',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'mat-005',
    project_id: 'proj-001',
    name: '방수액',
    category: 'plumbing',
    specification: '고탄성 수성',
    unit_price: 45000,
    quantity: 3,
    unit: '통',
    created_at: '2024-03-10T09:00:00Z',
  },
];

export const MOCK_ESTIMATE = {
  id: 'est-001',
  project_id: 'proj-001',
  file_url: '/mock/estimate.pdf',
  original_filename: '행복건설_견적서.pdf',
  total_amount: 28000000,
  status: 'completed' as const,
  overall_score: 72,
  risks: [
    {
      level: 'high' as const,
      title: '철거 폐기물 처리비 별도',
      description: '보통 30~80만원 추가 발생. 견적에 포함 여부 확인 필요',
    },
    {
      level: 'high' as const,
      title: '전기 추가 배선 현장 결정',
      description: '콘센트 추가 시 개당 3~5만원. 범위 미확정',
    },
    {
      level: 'medium' as const,
      title: '도배 면적 "실측 후 확정"',
      description: '면적 차이에 따라 ±10% 변동 가능',
    },
  ],
  missing_items: [
    { title: '입주청소 항목 없음', description: '보통 25평 기준 15~25만원. 포함인지 확인하세요' },
    { title: '보양 작업 항목 없음', description: '현관/엘리베이터 보양. 관리사무소 요구 시 추가' },
  ],
};

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    role: 'assistant',
    content:
      '안녕하세요! 공사 관련 뭐든 물어보세요.\n하자 진단, 비용 적정성, 업자에게 보낼 문구까지 도와드려요.',
  },
  {
    role: 'user',
    content: '타일 갈라졌는데 이거 하자보수 받을 수 있어?',
  },
  {
    role: 'assistant',
    content:
      '**타일 크랙 — 하자보수 가능합니다**\n\n**1. 하자 여부:** 시공 2개월 내 발생한 줄눈 크랙은 시공 하자에 해당합니다.\n\n**2. 법적 근거:** 건설산업기본법 시행령 별표4에 따라 타일 하자보수기간은 1년입니다.\n\n**3. 업자에게 보낼 카톡:**\n> "사장님, 욕실 타일 줄눈에 크랙이 발생했습니다. 시공 2개월 미만이라 하자보수 범위에 해당하는 것으로 보이는데, 확인 후 보수 일정 잡아주시면 감사하겠습니다."',
  },
];

export const INITIAL_SUGGESTIONS: string[] = [
  '이 견적 적정한가요?',
  '공사 중 확인할 것',
  '추가금 요구 대응법',
];

export const MOCK_FOLLOW_SUGGESTIONS: string[] = [
  '하자보수 요청서 작성해줘',
  '안 고쳐주면 어떡해?',
  '소비자원 신고 방법',
];

export const MOCK_STORAGE: StorageUsage = {
  used_bytes: 1288490188,
  limit_bytes: 5368709120,
  file_count: 78,
  file_limit: 500,
  plan: 'basic',
};

export const MOCK_UPLOAD_STEPS: UploadStep[] = [
  { label: '카카오톡 대화 파싱', status: 'completed', detail: '458개 메시지 추출됨' },
  { label: '사진 날짜 추출', status: 'completed', detail: '127장 EXIF 정보 추출' },
  { label: 'AI 공정 분류', status: 'processing', detail: '298/458 메시지 분류 완료', progress: 65 },
  { label: '타임라인 구성', status: 'pending' },
];
